# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 第一次人生
email: liuyangxtp@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    先视听读，后写之。
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://liuyangxtp.com" # the base hostname & protocol for your site
twitter_username: liuyangxtp
github_username:  LyingCortex

# Build settings
markdown: kramdown
