title:             第一次人生 First Life
email:             lyingcortex@outlook.com
description:       A Blog Owned by LY
author:            LY
baseurl:           ""
url:               "https://liuyangxtp.com"

# Social Profiles
twitter_username:  LyingCortex
github_username:   LyingCortex
facebook_username: You-Know-Who

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
